
# dbt_project.yml
# Configuração do projeto Adventure Works Analytics

name: 'fea_adventureworks'
version: '1.0.0'
config-version: 2

profile: 'fea_adventureworks'

# Estrutura de diretórios
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths:      ["docs"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

# Pacotes utilizados: packages.yml 
  # deve conter:
    # packages:
    #  - package: dbt-labs/dbt_utils
    #    version: 1.3.3
    #  - package: metaplane/dbt_expectations
    #    version: 0.10.10

models:
  fea_adventureworks:

    staging:
      +materialized: view
      +schema: stg_adw
    
    intermediate:
      +materialized: view
      +schema: int_adw

    marts:
      +materialized: table
      +schema: marts_adw
      dimentions:
        +materialized: table
      facts:
        +materialized: table

# Variáveis globais do projeto
vars:
  dbt_date:time_zone: 'America/São Paulo'
  audit_year: 2011
  audit_gross_revenue_2011: 12646112.16
